### ISSUE TITLE
what is the time zone of this component?

### ISSUE THREAD

**Issue by moshaabn** [TriDiamond/vuejs-countdown-timer#1]
I need to know what time zone this component use

**Comment by bennyxguo** [comment]
I did not specifically define the timezone when getting the default time, I basically just use `new Date().getTime()` which will get the current time from your browser. So basically if you didn't pass in the prop of current time, it will use the browser's time instead. 

In another word, different users in different timezone, will get the current time base on their browser. So if you are working on an APP that requires specific timezone, you could do that by passing your timezone's current time into the component.

`time` prop is the one you should use to pass in your current time either in **2018-09-26 14:36** format or **Unix timestamp**
