### ISSUE TITLE
minimizing window, then coming back to the window timer was not correctly executed

### ISSUE THREAD

**Issue by ho3einGh** [TriDiamond/vuejs-countdown-timer#10]
when i click or minimize window and see again countdown then counter not correctly run and counter run again

**Comment by bennyxguo** [comment]
> when i click or minimize window and see again countdown then counter not correctly run and counter run again

Do you mean minimizing your window, then coming back to the window, this usually would trigger a window reload. Did your page reloaded? How was it not correctly? What kind of problem did it occurred? Can you describe it better? Or more detail steps on how to reappear this issue.

**Comment by ho3einGh** [comment]
minimizing window, then coming back to the window  timer was not correctly executed 
for example in your demo site Time: Till starts: 00 days 00 hours 00 minutes 08.2 seconds when minimize window then come back (or click out of window then click on page) countdown reset and demo site timer:
Till starts: 00 days 00 hours 00 minutes 09.2 seconds 
 (without page reload just click) 

this problem evented before countdown timer ended

**Comment by bennyxguo** [comment]
> minimizing window, then coming back to the window timer was not correctly executed
> for example in your demo site Time: Till starts: 00 days 00 hours 00 minutes 08.2 seconds when minimize window then come back (or click out of window then click on page) countdown reset and demo site timer:
> Till starts: 00 days 00 hours 00 minutes 09.2 seconds
> (without page reload just click)
> 
> this problem evented before countdown timer ended

I can see the issue now, I will look into it, thanks for the feedback.

**Comment by bennyxguo** [comment]
@hosseinGh-ir
Fixed this problem on v2.1.2

## 2.1.2 (Oct 07, 2019)
### Bug fixes 🐛
- Fixed reenter the active window current time is not recalculated.
- Fixed event ended-callback triggered on vue mounted.
