### ISSUE TITLE
Don`t work on Safari MacOS and Safari iOS 

### ISSUE THREAD

**Issue by demchenkodenis** [TriDiamond/vuejs-countdown-timer#12]
In the demo the timer works, but when I copy the example code and open it in Safari, the timer is not displayed. 
Safari v12.1

**Comment by czaplinskim** [comment]
Hi! 

Your date format is probably Y-m-d H:i which is fine for most of browsers, but not for safari.

MDN:
> Note: parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.

Some browsers will try to parse the date even if it's not in a standard format. Safari will not.

So basically "2021-03-11 12:00:00" will not work, but 2021-03-11T12:00:00Z" will work properly even on Safari.

@TriDiamond if my answer is correct, you should consider converting all dates automatically to that format, so it will be displayed correctly on all browsers.

**Comment by bennyxguo** [comment]
> Hi!
> 
> Your date format is probably Y-m-d H:i which is fine for most of browsers, but not for safari.
> 
> MDN:
> 
> > Note: parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies. Support for RFC 2822 format strings is by convention only. Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are treated as UTC, not local.
> 
> Some browsers will try to parse the date even if it's not in a standard format. Safari will not.
> 
> So basically "2021-03-11 12:00:00" will not work, but 2021-03-11T12:00:00Z" will work properly even on Safari.
> 
> @TriDiamond if my answer is correct, you should consider converting all dates automatically to that format, so it will be displayed correctly on all browsers.

I will test that out tomorrow. Thanks for the suggestion.

**Comment by bennyxguo** [comment]
@demchenkodenis @czaplinskim Compatibility issue is fixed in version 2.1.3, you may go ahead and update your project. Especially thanks to @czaplinskim for pointing out the problems! Happy coding~
