### ISSUE TITLE
Removing day and hour display

### ISSUE THREAD

**Issue by Geowan** [TriDiamond/vuejs-countdown-timer#3]
How do i completely remove day and hour display

Currently i am having

                <vue-countdown-timer
                                v-if="!resend_active"
                                @start_callback="resend_active= false"
                                @end_callback="resend_active = true"
                                :start-time="new Date()"
                                :end-time="new Date().setMinutes(new Date().getMinutes()+2)"
                                :interval="1000"
                                :day-txt="null"
                                :hour-txt="null"
                                :minutes-txt="':'"
                                :seconds-txt="''"
                        >
                        </vue-countdown-timer>

I have tried seting them as null but they still display as 00 00

**Comment by bennyxguo** [comment]
@Geowan I will add this feature this month. Being extremely busy lately I should add it asap.

**Comment by diadal** [comment]
it will be great to add this feature so when day is 00 it will not display

**Comment by diadal** [comment]
may this will help you @Geowan 

```
<template slot="countdown" slot-scope="scope">
    <span v-if="scope.props.days != '00'">{{scope.props.days}}</span><i v-if="scope.props.days != '00'">{{scope.props.dayTxt}}</i>
    <span v-if="scope.props.hours != '00'">{{scope.props.hours}}</span v-if="scope.props.hours != '00'"><i >{{scope.props.hourTxt}}</i>
    <span v-if="scope.props.minutes != '00'">{{scope.props.minutes}}</span><i v-if="scope.props.minutes != '00'">{{scope.props.minutesTxt}}</i>}</span><i>{{scope.props.secondsTxt}}</i>
  </template>
 
```

**Comment by bennyxguo** [comment]
@Geowan I figure if you removed day and hour display, if you have a time greater than 60 minutes, I have to convert days, and hours into minutes. Else it will be weird. I still need to work on this feature for a bit. 

However I can quickly achieve what @diadal suggested, remove display if day or hour or minute reaches zero. I can give a prop to control that.

**Comment by diadal** [comment]
yes @Geowan I also working on it

**Comment by diadal** [comment]
this fix the min issue 

```

<template slot="countdown" slot-scope="scope">
    <span v-if="scope.props.days != '00'"><span>{{scope.props.days}}</span><i>{{scope.props.dayTxt}}</i></span>
    <span v-if="scope.props.hours != '00'"><span>{{scope.props.hours}}</span><i>{{scope.props.hourTxt}}</i></span>
    <span v-if="scope.props.minutes == '00' && scope.props.hours == '00'"></span>
    <span v-else><span>{{scope.props.minutes}}</span><i>{{scope.props.minutesTxt}}</i></span>
    <span>{{scope.props.seconds}}</span><i>{{scope.props.secondsTxt}}</i>
  </template>

```

**Comment by bennyxguo** [comment]
Added both of your features in `v2.1.0`
@Geowan @diadal 
#### Features
- Added the ability to auto hide when each unit's time reaches zero
- Added the ability to complete hide certain units

#### Bug fixes
- Fixed timestamp input for start time and end time not working

**Comment by diadal** [comment]
did you check this if 01Hour 00Min 33Sec with the new update hope 00Min won't hide @TriDiamond

**Comment by bennyxguo** [comment]
> did you check this if 01Hour 00Min 33Sec with the new update hope 00Min won't hide

The logic is like this, if you set to hide all 00, if any of the unit's count down reaches 00, it will hide. If you did not set to hide 00, 00 minutes will show. 

I am not sure if hiding 00 should be only for the condition when all previous times are 00, then they hide, the ones in between need to be shown. Which one is more suitable for all conditions.

**Comment by diadal** [comment]
Base on `I am not sure if hiding 00 should be only for the condition when all previous times are 00, then they hide, the ones in between need to be shown. Which one is more suitable for all conditions.`

the best to me show be like this if day = 00 then check if hour = 00 before hiding the hour for same for mins check day hour and min before hiding mins

```
<template slot="countdown" slot-scope="scope">
    <span v-if="scope.props.days != '00'"><span>{{scope.props.days}}</span><i>{{scope.props.dayTxt}}</i></span>

    <span v-if="scope.props.hours == '00' && scope.props.days == '00'"></span>
    <span v-else><span>{{scope.props.hours}}</span><i>{{scope.props.hourTxt}}</i></span>

    <span v-if="scope.props.minutes == '00' && scope.props.hours == '00' && scope.props.days == '00'"></span>
    <span v-else><span>{{scope.props.minutes}}</span><i>{{scope.props.minutesTxt}}</i></span>

    <span>{{scope.props.seconds}}</span><i>{{scope.props.secondsTxt}}</i>

  </template>

```

**Comment by bennyxguo** [comment]
> the best to me show be like this if day = 00 then check if hour = 00 before hiding the hour for same for mins check day hour and min before hiding mins

@diadal 

Yeah I have changed my logic to check previous unit is 00 (hidden), then the next unit will be hidden. Of cause unit hidden logic is bigger than this. So if you set the previous unit to be hidden, then the current unit will still be hidden. This is to prevent the condition where the current unit end up in the first unit due to the previous unit being set to hidden. 

## 2.1.1 (Feb 22, 2019)
### Changes
- Changed the hiding logic of 00s, only hide if all previous units are hidden.
- Changed the modification of the prop value, to avoid props changes in methods.
