### ISSUE TITLE
time in timestamp format 

### ISSUE THREAD

**Issue by diadal** [TriDiamond/vuejs-countdown-timer#4]
time in timestamp format  not working `:start-time="1570662000"
  :end-time="1573426800"`

**Comment by bennyxguo** [comment]
@diadal 
This problem fixed in `v2.1.0`, thanks a lot for the feedback!

#### Features
- Added the ability to auto hide when each unit's time reaches zero
- Added the ability to complete hide certain units

#### Bug fixes
- Fixed timestamp input for start time and end time not working
