### ISSUE TITLE
Avoid mutating a prop directly since

### ISSUE THREAD

**Issue by diadal** [TriDiamond/vuejs-countdown-timer#5]
`Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "startTime"`

`[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "endTime"`

**Comment by bennyxguo** [comment]
@diadal 
## 2.1.1 (Feb 22, 2019)
### Changes
- Changed the hiding logic of 00s, only hide if all previous units are hidden.
- Changed the modification of the prop value, to avoid props changes in methods.

Yeah found out I made a mistake of changing the props value during initial method, fixed it in `v2.1.1`, thanks for the feedback again!
