### ISSUE TITLE
time don't display on safari

### ISSUE THREAD

**Issue by diadal** [TriDiamond/vuejs-countdown-timer#8]
not working on safari browser why

**Comment by bennyxguo** [comment]
I will test it tonight to see what compatibility issue would cause this.

**Comment by diadal** [comment]
any update

**Comment by diadal** [comment]
hello were you able to fix this yet ??

**Comment by bennyxguo** [comment]
I have tested this on safari, time is displayed normally. Which version safari you have problem on?

**Comment by bennyxguo** [comment]
Duplicate of #12 
fixed in version 2.1.3
